### ISSUE TITLE
osticket equipment module

### ISSUE THREAD

**Issue by mtorres1** [poctob/OSTicketEquipment#2]
I installed the new version of osticket and installed the new build for the equipment module. Everything is working great except according to the wiki there should be and "equipment affected" and "ticket priority" blocks on the front end as well as the back end and they are not showing up for me. I enabled equipment, I gave groups rights BUT it shows those tabs for someone creating a ticket so not sure what is missing.
also everything works but when I add equipment I keep getting DB error even though when I check the DB the record is saved. I assume this is the reason the area I am talking about above is not showing. 

[SELECT et.ticket_id FROM ost_equipment_ticket et  LEFT JOIN ost_ticket ticket ON(et.ticket_id=ticket.ticket_id)  WHERE et.equipment_id=4 AND ticket.status='closed']

Table 'osticket.ost_equipment_ticket' doesn't exist<br /> <br />
---- Backtrace ----<br />
#0 C:\Inetpub\wwwroot\include\mysqli.php(132): osTicket->logDBError('DB Error #1146', '[SELECT et.tick...')<br />
#1 C:\Inetpub\wwwroot\include\class.equipment.php(160): db_query('SELECT et.ticke...')<br />
#2 C:\Inetpub\wwwroot\include\staff\equipment_view.inc.php(144): Equipment::getClosedTickets('4')<br />
#3 C:\Inetpub\wwwroot\scp\equipment_item.php(98): require_once('C:\Inetpub\wwwr...')<br />
#4 {main}

**Comment by poctob** [comment]
Make sure that you have **added** and **published** at least one equipment category, at least one equipment status (better to have two, one should be the baseline, i.e. fully operational), and at least one equipment item.  
Ticket priority has been removed from the front end by osTicket team.  It is still in the backend further down the form and it is called "priority level" now.

**Comment by mtorres1** [comment]
Thanks for the quick reply

I have three status (one is baseline) - 2 categories and 3 equipment and I still get this error. also nothing is showing up when you create a new ticket. We need the ability to attach a ticket to the equipment just like the wiki shows. Do I need to add that table to the DB? I just don't know what row to add
[SELECT et.ticket_id FROM ost_equipment_ticket et  LEFT JOIN ost_ticket ticket ON(et.ticket_id=ticket.ticket_id)  WHERE et.equipment_id=6 AND ticket.status='closed']

Table 'osticket.ost_equipment_ticket' doesn't exist<br /> <br />
---- Backtrace ----<br />
#0 C:\Inetpub\wwwroot\include\mysqli.php(132): osTicket->logDBError('DB Error #1146', '[SELECT et.tick...')<br />
#1 C:\Inetpub\wwwroot\include\class.equipment.php(160): db_query('SELECT et.ticke...')<br />
#2 C:\Inetpub\wwwroot\include\staff\equipment_view.inc.php(144): Equipment::getClosedTickets('6')<br />
#3 C:\Inetpub\wwwroot\scp\equipment_item.php(98): require_once('C:\Inetpub\wwwr...')<br />
#4 {main}

Also I have done a fresh install several times starting with osticket then adding the module. Is there anyway I can get a file with the default tables the module creates so I can add them back into the DB. Obviously the only thing that is not changing when I do the upgrade and fresh installs is the DB, so something is wrong in the DB for sure. There have been many configurations saved already in the DB so I would like to avoid creating it from scratch.

**Comment by mtorres1** [comment]
These are the only tables for equipment showing up in my DB

![image](https://f.cloud.github.com/assets/6494966/1998657/bd8c33ae-8537-11e3-94c6-f0d30f4cf6e9.png)

**Comment by poctob** [comment]
Looks like you are missing that table, here is the code to generate one, make sure that you've selected osticket as your database:

```
CREATE TABLE ost_equipment_ticket` (
  `equipment_id` int(11) NOT NULL,
  `ticket_id` int(11) NOT NULL,
  `created` date NOT NULL,
  PRIMARY KEY (`equipment_id`,`ticket_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by mtorres1** [comment]
Now I am getting this error when I try and save
![image](https://f.cloud.github.com/assets/6494966/1999083/90e52066-853e-11e3-88c1-d9df613f93d6.png)

**Comment by mtorres1** [comment]
![image](https://f.cloud.github.com/assets/6494966/1999192/171e0f8e-8540-11e3-9a2e-86e5667a6136.png)

**Comment by poctob** [comment]
OK, so the issue is with the database configuration.  Try this script:

```
CREATE TABLE ost_equipment_ticket` (
  `equipment_id` int(11) NOT NULL,
  `ticket_id` int(11) NOT NULL,
  `created` date NOT NULL,
  PRIMARY KEY (`equipment_id`,`ticket_id`)
);

```

**Comment by mtorres1** [comment]
is there a way to force this module to do a fresh install and just add the missing items? When I get it to do the fresh install it obviously starts yapping about duplicate tables and so forth and even when I delete everything is still gives me errors. I keep getting the same error

**Comment by mtorres1** [comment]
I got it fixed by repairing the DB but I still do not see that option it shows here - I have several of each option created (equipment, status ext..)
![image](https://f.cloud.github.com/assets/6494966/2000284/fa61313a-8555-11e3-9f0d-6f0d026ad16f.png)
