### ISSUE TITLE
Use of undefined constant USER_TABLE

### ISSUE THREAD

**Issue by freeload101** [poctob/OSTicketEquipment#4]
base install logged in and dumped files check perms to 777 and still have issue :+1: 

==> /var/log/apache2/error.log <==
[Sat Jan 02 00:12:45.017967 2016] [:error] [pid 8063] [client 172.16.251.25:64311] PHP Notice:  Use of undefined constant USER_TABLE - assumed 'USER_TABLE' in /var/www/html/include/class.orm.php on line 116
[Sat Jan 02 00:12:45.018061 2016] [:error] [pid 8063] [client 172.16.251.25:64311] PHP Notice:  Use of undefined constant USER_EMAIL_TABLE - assumed 'USER_EMAIL_TABLE' in /var/www/html/include/class.orm.php on line 124
[Sat Jan 02 00:12:45.018163 2016] [:error] [pid 8063] [client 172.16.251.25:64311] PHP Fatal error:  Class 'AuthenticatedUser' not found in /var/www/html/include/class.client.php on line 166

running osTicket-v1.8.12.zip on Ubuntu 14.04.3 LTS

**Comment by poctob** [comment]
This is a deprecated mod, see
https://github.com/poctob/OSTEquipmentPlugin
